services:
  - type: web
    name: network-fusion-backend
    env: docker
    autoDeploy: true
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://network-fusion-backend.onrender.com
