services:
  - type: web
    name: network-fusion-backend
    env: docker
    rootDir: backend-laravel
    dockerfilePath: backend-laravel/Dockerfile
    dockerContext: backend-laravel
    autoDeploy: true
    healthCheckPath: /up
    plan: free
