services:
  - type: web
    name: network-fusion-backend
    env: docker
    rootDir: backend-laravel
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /api/health
    plan: free
